# -*- coding: utf-8 -*-
"""AulasPython.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PDJXUnFbfcTAEaWAN66W6Vkpizl8B5Bb
"""

a = -5
b= 8
c = a+b
print(c)

idade = int(input('Digite sua idade: '))
print('Sua idade é : ',idade)

m = c* idade
print(m)

a = 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'
maiuscula = a.upper()
print(maiuscula)

nome = str('gabriel reis')
tamanho = int(len(nome))
capital = nome.capitalize()
print(capital)
print(tamanho)
i=0

p=nome.find(' ')
print(p)
nc = str(nome[0:p])
nc = nc.capitalize()
capital=nome[p+1:].capitalize()
print(capital)
print(nc)

a = 4**2
b = 8**3
c = a/b
print(a,b,round(c,3))

"""## **Ler dois números inteiros, executar e mostrar o resultado das seguintes operações: adição, subtração, multiplicação e divisão**"""

a= int(input('Digite o primeiro numero: '))
b= int(input('Digite o segundo numero: '))
print (f'A soma de {a} e {b} é: ',abs(a+b))
print (f'A subtração de {a} e {b} é: ',a-b)
print (f'A multiplicação de {a} e {b} é: ',a*b)
print (f'A divisão de {a} e {b} é: ',a/b)

"""## **Efetuar o cálculo da quantidade de litros de combustível gasto em uma viagem, utilizando um automóvel que faz 12 Km por litro. Para obter o cálculo, o usuário deve fornecer o tempo gasto na viagem e a velocidade média durante ela. Desta forma, será possível obter a distância percorrida com a fórmula DISTANCIA = TEMPO * VELOCIDADE. Tendo o valor da distância, basta calcular a quantidade de litros de combustível utilizada na viagem, com a fórmula: LITROS_USADOS = DISTANCIA / 12. O programa deve apresentar os valores da velocidade média, tempo gasto na viagem, a distância percorrida e a quantidade de litros utilizada na viagem**"""

tempo = int(input('Digite o tempo gasto na viagem(em Horas): '))
vm = int(input('Digite a valocidade media durante a viagem(em Km/h): '))
distancia = tempo*vm
litros_usados = distancia/12
print(f'\nO tempo de duração da viagem foi {tempo} Horas \nA velocidade media da viagem foi de {vm} Km/h \nA distancia percorrida foi {distancia} km \nA quantidade de litros utilizada na viagem foi {round(litros_usados,2)} litros')
